### ISSUE TITLE
Profiling configuration not working

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/pyroscope-java#110]
I am using the below configuration, 

> PYROSCOPE_APPLICATION_NAME=PetClinic
> PYROSCOPE_LOG_LEVEL=debug
> PYROSCOPE_SERVER_ADDRESS=https://pyroscope.XXXXX.click
> 
>  java -javaagent:/home/vamsi/pyroscope.jar -jar spring-petclinic-3.1.0-SNAPSHOT.jar

Getting the below error:

> 2023-08-29 16:35:57.262 [ERROR] Error starting profiler java.lang.IllegalStateException: java.lang.IllegalStateException: ITIMER_PROF is not supported on this system

When I set PYROSCOPE_FORMAT to jrf or set PYROSCOPE_PROFILER_EVENT to anything other than itimer, I am getting below error:

> 2023-08-29 16:34:26.580 [ERROR] Error uploading snapshot: 404
> 2023-08-29 16:34:26.581 [DEBUG] Backing off for 1382 ms
> 2023-08-29 16:34:27.967 [DEBUG] Upload attempt 3. collapsed: 983625
> 2023-08-29 16:34:28.102 [ERROR] Error uploading snapshot: 404

Can someone please help?

**Comment by Rperry2174** [comment]
hi @mvkrishna86 can you tell use more information about your environment that this is running on ?

**Comment by mvkrishna86** [comment]
OS: Ubuntu 22.04.1
Java: openjdk version "17.0.8"

vamsi@NHHYDL-02026:~/spring-petclinic/target$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

vamsi@NHHYDL-02026:~/spring-petclinic/target$ java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Ubuntu-122.04, mixed mode, sharing)

**Comment by mvkrishna86** [comment]
@Rperry2174 , any idea what is wrong here? 
I am using latest pyroscope jar. Tried in multiple environments, still getting 404 error.

**Comment by korniltsev** [comment]
@mvkrishna86 is it working now?

**Comment by mvkrishna86** [comment]
Yes. It's working fine now.
