### ISSUE TITLE
Ability to turn profiling off at runtime

### ISSUE THREAD

**Issue by Krithika3** [grafana/pyroscope-java#119]
Today, if we have to turn off profiling to avoid excessive consumption of resources we have to redeploy the app to stop profiling, is there a way to turn off profiling at runtime

**Comment by Krithika3** [comment]
@korniltsev is the a reasonable ask? Thanks

**Comment by Krithika3** [comment]
I would like to contribute to this if I can, any pointers to help me get started would be appreciated :)Thanks

**Comment by corona10** [comment]
We need this feature in our corp production, too.

**Comment by aleks-p** [comment]
done with https://github.com/grafana/pyroscope-java/pull/149
