### ISSUE TITLE
Java agent does not work with Java Flight Recorder

### ISSUE THREAD

**Issue by charlesverdad** [grafana/pyroscope-java#12]
I can't run pyroscope-java agent with the Java flight recorder (`-XX:StartFlightRecording` flag).

```sh
15:41:51 ❯ java -XX:-Inline -XX:StartFlightRecording -javaagent:pyroscope.jar Main
2022-01-24 15:41:58.002 INFO PyroscopeAgent We recommend specifying application name via env variable PYROSCOPE_APPLICATION_NAME
2022-01-24 15:41:58.025 INFO PyroscopeAgent For now we chose the name for you and it's javaspy.UaQzrZeWTfGFueCnID015w
2022-01-24 15:41:58.025 WARN PyroscopeAgent PYROSCOPE_SERVER_ADDRESS is not defined, using http://localhost:4040
2022-01-24 15:41:58.255 INFO PyroscopeAgent Profiling started
[1]    91159 illegal hardware instruction  java -XX:-Inline -XX:StartFlightRecording -javaagent:pyroscope.jar Main

```

## Steps to reproduce

- Copy `Main.java` from the [java example in the main repo](https://github.com/pyroscope-io/pyroscope/blob/main/examples/java/Main.java)
- Compile it and then run with `-XX:StartFlightRecording` flag

```sh
javac Main.java
java -XX:-Inline -XX:StartFlightRecording -javaagent:pyroscope.jar Main
```

Error:
```
[1]    91159 illegal hardware instruction  java -XX:-Inline -XX:StartFlightRecording -javaagent:pyroscope.jar Main
```

OS: MacOS 11.6.1 Big Sur (intel)

If I run it inside docker I get `java_app_1 exited with code 139`

## Expected behaviour

From my understanding the java pyroscope agent uses `async-profiler` under the hood. And because async-profiler works even with Java flight recorder enabled, I expect pyroscope to work too.

Java app with flight recorder and without pyroscope:

```sh

15:47:18 ❯ java -XX:-Inline -XX:StartFlightRecording  Main
Started recording 1. No limit specified, using maxsize=250MB as default.

Use jcmd 92349 JFR.dump name=1 filename=FILEPATH to copy recording data to file.
```

Running async-profiler on the java process works even with flight recorder:

```sh
15:47:06 ❯ ./profiler.sh -e cpu,alloc,lock -f profile2.jfr 92349
Profiling for 60 seconds
Done
```

The async-profiler worked with flight recorder, so I was expecting pyroscope to work too.

**Comment by netamego** [comment]
Hi,
The problem here is that pyroscope use collapsed output which is a plain text format. 

From https://github.com/jvm-profiling-tools/async-profiler

`collapsed - dump collapsed call traces in the format used by FlameGraph script. This is a collection of call stacks, where each line is a semicolon separated list of frames followed by a counter`

I think jfr ouput can't be read directly without the proper tool or some type of conversion like async profiler do:

```
Converters between profile formats: converter.jar
(JFR to Flame Graph, JFR to FlameScope, collapsed stacks to Flame Graph)
```
Maybe you can do all the stuff with a shell script and then POST to pyroscope server. From tcpdump you can see how to post. Something like:

```
POST /ingest?name=miapp&units=samples&aggregationType=sum&sampleRate=100&from=1643043700&until=1643043710&spyName=javaspy HTTP/1.1
User-Agent: Java/1.8.0_144
Host: localhost:4040
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-type: application/x-www-form-urlencoded

<<collapsed-output-obtained with ./profiler.sh and converted from ffr>> 
```

I am talking to talk. It's an idea. I have not tried it.

**Comment by netamego** [comment]
Hi,
This a duplicate issue. Same was reported in #3 I think this issue should be closed.
Best regards.

**Comment by Rperry2174** [comment]
This is now implemented!

- [Docs](https://pyroscope.io/docs/java/#labels)
- [Examples](https://github.com/pyroscope-io/pyroscope/blob/main/examples/java-jfr/rideshare/README.md)

**Comment by kong62** [comment]
2023-03-20 15:12:43.413 [WARN] Invalid PYROSCOPE_PROFILER_EVENT value cpu,alloc, using itimer

**Comment by aleks-p** [comment]
I was able to run this with the latest version of the agent and Java 17. If you are still experiencing issues let us know and provide detailed information (OS, arch, Java version, etc.)
