### ISSUE TITLE
Reduce boilerplate code through the use of Lombok

### ISSUE THREAD

**Issue by zalintyre** [grafana/pyroscope-java#124]
I'd like to propose the use of [Project Lombok](https://projectlombok.org/) to reduce boilerplate code like equals, toString, hashcode and many more. What do you think?

**Comment by zalintyre** [comment]
I created a draft PR so you can see what I was thinking of: #127

**Comment by korniltsev** [comment]
Hello,

Thank you for your contribution. After reviewing the changes, I'd like to share a few thoughts:

- The code you referred to as "boilerplate" appears essential in both the before and after cases. I appreciate its purpose and believe it's not superfluous.
- While Lombok has its merits, I personally feel it somewhat diverges from the core Java principles. For the sake of keeping the project consistent, I'd prefer we stick to standard Java.
- In terms of dependencies, my aim for this project is to minimize them as much as possible, including potentially removing existing ones like okhttp and the transitive kotlin stdlib.

I hope you understand my perspective. I value your efforts and would welcome further discussions on improving the project.
