### ISSUE TITLE
Separate components by usage of dependency injection with CDI

### ISSUE THREAD

**Issue by zalintyre** [grafana/pyroscope-java#125]
Coupling of components can be lowered using a dependency injection mechanism. I'd like to propose the use of CDI (Contexts and dependency injection). It is entirely usable with Java SE:

https://www.baeldung.com/java-ee-cdi

**Comment by korniltsev** [comment]
What problem does it solve?

**Comment by zalintyre** [comment]
It mainly solves the problem of unit-testing separate components (units) instead of having to test the whole call-chain. This would be more of an integration test.

**Comment by korniltsev** [comment]
We don't have this problem
