### ISSUE TITLE
Support Async Profiler ctimer event

### ISSUE THREAD

**Issue by SeekDaSky** [grafana/pyroscope-java#144]
`ctimer` is a new event added in Async Profiler 3 ([issue here](https://github.com/async-profiler/async-profiler/issues/855)) which gives the same benefits as `itmer` while being much more reliable. 

There is currently no way to use this new event as far as I can see. One downside is that it is not available in MacOS and I do not know what `pyroscope-java` policy is around OS specific features.

It would be grand to be able to use it with pyroscope.

**Comment by korniltsev** [comment]
https://github.com/grafana/pyroscope-java/pull/145

**Comment by SeekDaSky** [comment]
Is there any release of this library planned so we can take advantage of `ctimer` ?

**Comment by korniltsev** [comment]
I've just pushed 0.13.1

**Comment by SeekDaSky** [comment]
Thank you so much for your work 😄
