### ISSUE TITLE
Feature flag to disable Pyroscope agent

### ISSUE THREAD

**Issue by kazuhiro** [grafana/pyroscope-java#68]
Some java agents (for instance New Relics: https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/disable-apm-agent/) have an option to temporarily disable them via configuration parameter for the purposes of testing or troubleshooting. It is much harder to achieve the same thing by modification of javagent paths, because quite often they are hardcoced by packaging tools (ie. in sbt). Something like:
```
-Dpyroscope.agent_enabled=false
```
would do the job. Wdyt?

**Comment by zalintyre** [comment]
I would like to have a look at this issue.
